# frozen_string_literal: true

# SecretsController — exposes secret values as JSON for test verification.
#
# Bella Baxter's Railtie injects all secrets into ENV at before_configuration,
# before this controller is ever loaded. Two patterns shown:
#
#   GET /secrets  — raw ENV strings (classic Rails way)
#   GET /typed    — typed values via AppSecrets (generated module, app/lib/app_secrets.rb)
class SecretsController < ApplicationController
  SECRET_KEYS = %w[
    PORT DATABASE_URL EXTERNAL_API_KEY GLEAP_API_KEY
    ENABLE_FEATURES APP_ID ConnectionStrings__Postgres APP_CONFIG
  ].freeze

  # GET /
  def index
    render json: {
      message: "Hello from Bella Baxter + Rails",
      secrets_loaded: SECRET_KEYS.count { |k| ENV.key?(k) },
    }
  end

  # GET /health
  def health
    render json: { ok: true }
  end

  # GET /secrets — raw string values from ENV
  def show
    render json: SECRET_KEYS.each_with_object({}) { |k, h| h[k] = ENV.fetch(k, "") }
  end

  # GET /typed — type-cast values via AppSecrets
  #
  # AppSecrets is generated by `bella secrets generate ruby` and lives in
  # app/lib/app_secrets.rb. It reads from ENV (already populated by the Railtie)
  # and returns properly typed values: Integer, Boolean, URI, parsed JSON Struct.
  def typed
    cfg = AppSecrets.app_config
    render json: {
      "PORT"                        => AppSecrets.port,            # Integer
      "DATABASE_URL"                => AppSecrets.database_url.to_s,
      "EXTERNAL_API_KEY"            => AppSecrets.external_api_key,
      "GLEAP_API_KEY"               => AppSecrets.gleap_api_key,
      "ENABLE_FEATURES"             => AppSecrets.enable_features, # Boolean
      "APP_ID"                      => AppSecrets.app_id,
      "ConnectionStrings__Postgres" => AppSecrets.connection_string,
      "APP_CONFIG"                  => { "setting1" => cfg.setting1, "setting2" => cfg.setting2 },
    }
  end
end
