# auto-generated by: bella secrets generate ruby
# project: my-project/production/vault
# generated at: 2025-01-15 10:30:00 UTC
# DO NOT edit manually — re-run bella secrets generate ruby to update.
# frozen_string_literal: true

require 'json'
require 'securerandom'
require 'uri'

module AppSecrets
  AppConfigShape = Struct.new(:setting1, :setting2, keyword_init: true)

  def self._require(key)
    ENV.fetch(key) { raise "Required env var '#{key}' is not set." }
  end

  # String — third-party API key
  def self.external_api_key = _require("EXTERNAL_API_KEY")

  # Int — HTTP server port
  def self.port = _require("PORT").to_i

  # Bool — enable features toggle
  def self.enable_features = _require("ENABLE_FEATURES") == "true"

  # Uri — PostgreSQL connection string
  def self.database_url
    url = _require("DATABASE_URL")
    begin
      URI.parse(url)
    rescue URI::InvalidURIError
      # Return a duck-typed object for non-standard URIs (e.g. placeholder with non-numeric port)
      parts = url.match(%r{^(\w+)://[^@]*@([^:/]+)})
      Struct.new(:scheme, :host).new(parts&.[](1) || "unknown", parts&.[](2) || "unknown")
    end
  end

  # JSON — application configuration
  def self.app_config
    data = JSON.parse(_require("APP_CONFIG"), symbolize_names: true)
    AppConfigShape.new(
      setting1: data[:setting1],
      setting2: data[:setting2],
    )
  end

  # GUID — application instance ID
  def self.app_id = _require("APP_ID")
end
