# frozen_string_literal: true

require "json"
require "openssl"
require "digest"
require "time"
require "microsoft_kiota_faraday"
require_relative "hmac_auth_provider"
require_relative "e2ee_faraday_middleware"
require_relative "models"
require_relative "errors"
require_relative "e2ee"

# require generated Kiota client (generated by apps/sdk/generate.sh)
begin
  require_relative "generated/bella_client"
rescue LoadError
  # generated/ not present — run apps/sdk/generate.sh to generate the Kiota client
end

module BellaBaxter
  # Thread-safe Bella Baxter API client backed by the Kiota-generated BellaClient.
  #
  # Instantiate once and reuse across requests (e.g. in a Rails initializer).
  # End-to-end encryption is always enabled — secret values are never visible
  # in plaintext over the wire.
  #
  # == Basic usage
  #
  #   client = BellaBaxter::Client.new(
  #     baxter_url: "https://baxter.example.com",
  #     api_key:    "bax-..."
  #   )
  #   secrets = client.all_secrets.secrets
  #   ENV["DATABASE_URL"] = secrets["DATABASE_URL"]
  #
  # Prerequisites: run `apps/sdk/generate.sh` to generate `lib/bella_baxter/generated/` first.
  class Client
    # Convenience constructor — reads BELLA_API_KEY and BELLA_BAXTER_URL from ENV.
    #
    # @return [BellaBaxter::Client]
    def self.from_env
      new(
        baxter_url: ENV.fetch("BELLA_BAXTER_URL", "https://api.bella-baxter.io"),
        api_key:    ENV.fetch("BELLA_API_KEY")
      )
    end

    # @param opts [Hash, BellaBaxter::Configuration]
    def initialize(**opts)
      config = opts.size == 1 && opts.key?(:config) ? opts[:config] : Configuration.new(**opts)

      auth = HmacAuthProvider.new(config.api_key)

      @conn = Faraday.new(url: config.baxter_url.chomp("/")) do |f|
        f.headers["User-Agent"]     = "bella-ruby-sdk/1.0"
        f.headers["X-Bella-Client"] = "bella-ruby-sdk"
        f.use E2EEFaradayMiddleware
        f.adapter :net_http
      end

      adapter = MicrosoftKiotaFaraday::FaradayRequestAdapter.new(auth, nil, nil, @conn)
      adapter.set_base_url(config.baxter_url.chomp("/"))

      @kiota  = BellaBaxterGenerated::BellaClient.new(adapter)
      @config = config
    end

    # ── Key context (auto-discovery) ────────────────────────────────────────────

    # Calls GET /api/v1/keys/me to discover the project + environment this key
    # is scoped to. Result is cached for the lifetime of the client instance.
    #
    # @return [Hash] parsed JSON response with 'projectSlug', 'environmentSlug', etc.
    def key_context
      @key_context ||= begin
        parts     = @config.api_key.split("-", 3)
        key_id    = parts[1]
        secret    = [parts[2]].pack("H*")
        path      = "/api/v1/keys/me"
        timestamp = Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")
        body_hash = Digest::SHA256.hexdigest("")
        sts       = "GET\n#{path}\n\n#{timestamp}\n#{body_hash}"
        signature = OpenSSL::HMAC.hexdigest("SHA256", secret, sts)

        resp = @conn.get(path) do |req|
          req.headers["Accept"]            = "application/json"
          req.headers["X-Bella-Key-Id"]    = key_id
          req.headers["X-Bella-Timestamp"] = timestamp
          req.headers["X-Bella-Signature"] = signature
        end
        JSON.parse(resp.body)
      end
    end

    # ── Secret reads ────────────────────────────────────────────────────────────

    # Fetch all secrets. Project and environment are auto-discovered from the API key.
    # Can be overridden via keyword args for advanced use cases.
    #
    # @return [BellaBaxter::AllSecretsResponse]
    def all_secrets(project: nil, environment: nil)
      ctx         = key_context
      project     ||= ctx["projectSlug"]
      environment ||= ctx["environmentSlug"]

      resp = @kiota.api.v1.projects.by_id(project)
        .environments.by_env_slug(environment).secrets.get.resume

      secrets = resp&.secrets&.additional_data || {}

      AllSecretsResponse.new(
        environment_slug: resp&.environment_slug || environment,
        environment_name: resp&.environment_name || "",
        secrets:          secrets.transform_values(&:to_s),
        version:          resp&.version || 0,
        last_modified:    resp&.last_modified&.to_s || ""
      )
    end

    # Convenience: fetch all secrets and return them as a plain Hash.
    #
    # @return [Hash<String, String>]
    def pull_secrets(project: nil, environment: nil)
      all_secrets(project: project, environment: environment).secrets
    end

    # Lightweight version check. Project/environment auto-discovered from the API key.
    #
    # @return [BellaBaxter::SecretsVersionResponse]
    def secrets_version(project: nil, environment: nil)
      ctx         = key_context
      project     ||= ctx["projectSlug"]
      environment ||= ctx["environmentSlug"]

      resp = @kiota.api.v1.projects.by_id(project)
        .environments.by_env_slug(environment).secrets.version.get.resume

      SecretsVersionResponse.new(
        environment_slug: resp&.environment_slug || environment,
        version:          resp&.version || 0,
        last_modified:    resp&.last_modified&.to_s || ""
      )
    end

    # Convenience: load all secrets into ENV.
    #
    # Secrets that are already set in ENV are NOT overwritten (existing
    # environment variables take precedence — useful for local dev overrides).
    #
    # @param overwrite [Boolean] force-overwrite existing ENV values (default: false)
    # @return [Integer] number of secrets injected
    def load_into_env!(project: nil, environment: nil, overwrite: false)
      resp  = all_secrets(project: project, environment: environment)
      count = 0
      resp.secrets.each do |key, value|
        next if !overwrite && ENV.key?(key)
        ENV[key] = value
        count   += 1
      end
      count
    end

    # Access the full Kiota API navigator for all other endpoints
    # (TOTP, projects, providers, environments, etc.).
    #
    # Example:
    #   client.client.api.v1.projects.by_id("my-app")
    #     .environments.by_env_slug("prod").totp.get
    def client
      @kiota
    end
  end
end
